medicalsys/core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('patients.urls')),
    path('', include('schedule.urls'))
]

medicalsys/patients/urls.py
from django.urls import path

from .views import (create_patient, delete_patient, edit_patient,
                    list_patients, patient_id)

urlpatterns = [
    path('patients/add', create_patient, name='create_patient'),
    path('patients/list', list_patients, name='list_patients'),
    path('patients/<int:pk>', patient_id, name='patient_id'),
    path('patients/<int:pk>/edit',
         edit_patient, name='edit_patient'),
    path('patients/<int:pk>/delete',
         delete_patient, name='delete_patient')
]

medicalsys/patients/models.py
from django.db import models
from django.utils import timezone


class Patient(models.Model):
    name = models.CharField('patient name', max_length=100)
    phone = models.CharField('phone number', max_length=15)
    address = models.CharField('address', max_length=255)
    address_number = models.CharField('address number', max_length=100)
    city = models.CharField('city', max_length=100)
    uf = models.CharField('UF', max_length=2)
    country = models.CharField('country', max_length=100)
    cep = models.CharField('CEP', max_length=9)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

medicalsys/patients/forms.py
from django import forms

from .models import Patient


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ['created_at']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'minlength': 14}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'address_number': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'uf': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'cep': forms.TextInput(attrs={'class': 'form-control', 'minlength': 9}),
        }
        labels = {
            'name': 'Nome',
            'phone': 'Telefone',
            'address': 'Endereço',
            'address_number': 'Número',
            'city': 'Cidade',
            'uf': 'UF',
            'country': 'País',
            'cep': 'CEP'
        }

medicalsys/patients/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PatientForm
from .models import Patient


@login_required
def create_patient(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)

        if form.is_valid():
            form.save()
            form = PatientForm()
            messages.success(request, 'Paciente cadastrado com sucesso!')
            return redirect('list_patients')
        else:
            messages.error(request, 'Dados inválidos!')
            context = {'form': form}
            return render(request, 'patients/add.html', context)

    else:
        form = PatientForm()
        context = {'form': form}
        return render(request, 'patients/add.html', context)


@login_required
def list_patients(request):
    patients = Patient.objects.all()
    context = {'patients': patients}
    return render(request, 'patients/list.html', context)


@login_required
def edit_patient(request, pk):
    patient = get_object_or_404(Patient, id=pk)

    if request.method == 'POST':
        form = PatientForm(request.POST, instance=patient)

        if form.is_valid():
            form.save()
            form = PatientForm()
            messages.success(request, 'Paciente atualizado com sucesso!')
            return redirect('list_patients')

    else:
        form = PatientForm(instance=patient)
        context = {'form': form, 'patient': patient}
        return render(request, 'patients/edit.html', context)


@login_required
def delete_patient(request, pk):
    patient = get_object_or_404(Patient, id=pk)

    if request.method == 'POST':
        patient.delete()
        messages.success(request, 'Paciente deletado com sucesso!')
        return redirect('list_patients')

    else:
        context = {'patient': patient}
        return render(request, 'patients/delete.html', context)


@login_required
def patient_id(request, pk):
    patient = get_object_or_404(Patient, id=pk)
    context = {'patient': patient}
    return render(request, 'patients/id.html', context)

medicalsys/templates/patients/partials/inputs.html
<div class="col-md-12">
  <label for="{{ form.name.id_for_label }}" class="form-label">{{ form.name.label }}</label>
  {{ form.name }}
</div>

<div class="col-md-6">
  <label for="{{ form.phone.id_for_label }}" class="form-label">{{ form.phone.label }}</label>
  {{ form.phone }}
</div>

<div class="col-md-6">
  <label for="{{ form.cep.id_for_label }}" class="form-label">{{ form.cep.label }}</label>
  {{ form.cep }}
</div>

<div class="col-md-9">
  <label for="{{ form.address.id_for_label }}" class="form-label">{{ form.address.label }}</label>
  {{ form.address }}
</div>

<div class="col-md-3">
  <label for="{{ form.address_number.id_for_label }}" class="form-label">{{ form.address_number.label }}</label>
  {{ form.address_number }}
</div>

<div class="col-md-4">
  <label for="{{ form.city.id_for_label }}" class="form-label">{{ form.city.label }}</label>
  {{ form.city }}
</div>

<div class="col-md-4">
  <label for="{{ form.uf.id_for_label }}" class="form-label">{{ form.uf.label }}</label>
  {{ form.uf }}
</div>

<div class="col-md-4">
  <label for="{{ form.country.id_for_label }}" class="form-label">{{ form.country.label }}</label>
  {{ form.country }}
</div>

<!-- Modal CEP error-->
<div class="modal fade" id="cepErrorModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="cepErrorModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="cepErrorModalLabel">CEP inválido</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Verifique se o CEP é válido!!!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<!-- Inputs masks -->
<script>
  // Phone mask
  $(document).ready(function () {
    const mobileMask = "(00) 00009-0000";
    const landlineMask = "(00) 0000-0000";

    $("#id_phone").mask(mobileMask);

    $("#id_phone").keyup(function (event) {
      const isMobile = $(this).val().substring(5, 6) == 9;

      phoneLengthValidation(isMobile)

      setPhoneMask(isMobile)
    });

    // Bypass HTML minlength validation because mask use
    function phoneLengthValidation(isMobile) {
      const len = $("#id_phone").val().length;

      if (!isMobile && len < 14) {
        $("#id_phone")[0].setCustomValidity("Please use at least 14 characters")

      } else if (isMobile && len < 15) {
        $("#id_phone")[0].setCustomValidity("Please use at least 15 characters")

      } else {
        $("#id_phone")[0].setCustomValidity("")
      }
    }

    function setPhoneMask(isMobile) {
      if (isMobile) {
        $("#id_phone").mask(mobileMask);
      } else {
        $("#id_phone").mask(landlineMask);
      }
    }
  });

  // CEP mask
  $(document).ready(function () {
    $("#id_cep").mask("00000-000");

    $("#id_cep").keyup(function (event) {
      cepLengthValidation()
    })

    // Bypass HTML minlength validation because mask use
    function cepLengthValidation(length) {
      const len = $("#id_cep").val().length;

      if (len < 9) {
        $("#id_cep")[0].setCustomValidity("Please use at least 9 characters")

      } else {
        $("#id_cep")[0].setCustomValidity("")
      }
    }
  });
</script>

<!-- Fetch CEP -->
<script>
  $(document).ready(function () {
    let previousCepValue = "";

    $("#id_cep").keyup(function (event) {
      const cep = $(this).val();
      const cepNumeric = cep.replace(/\D/g, '');

      const hasCepChanged = cepNumeric !== previousCepValue

      if (hasCepChanged && cepNumeric.length === 8) {
        previousCepValue = cepNumeric;

        getAddressInfo(cepNumeric)
      }
    })

    function getAddressInfo(cep) {
      $.get("https://viacep.com.br/ws/" + cep + "/json/", function (data) {
        if (!data.erro) {
          autoFillAddressFields(data)

          focusToAddressNumberField()
        } else {
          openCepErrorModal()

          cleanAddressFields()
        }
      });
    }

    function autoFillAddressFields(data) {
      $("#id_address").val(data.logradouro)
      $("#id_city").val(data.localidade)
      $("#id_uf").val(data.uf)
      $("#id_country").val("Brasil")
    }

    function focusToAddressNumberField() {
      $("#id_address_number").val("")
      $("#id_address_number").focus()
    }

    function openCepErrorModal() {
      $("#cepErrorModal").modal("show")
    }

    function cleanAddressFields() {
      $("#id_address").val("")
      $("#id_address_number").val("")
      $("#id_city").val("")
      $("#id_uf").val("")
      $("#id_country").val("")
    }
  })
</script>